apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-platform-file-server
  labels:
      app: sports-platform-file-server
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: sports-platform-file-server
      template:
        metadata:
          labels:
            app: sports-platform-file-server
        spec:
          containers:
          - name: sports-platform-file-server
            image: biuea/sports-platform-file-server
            env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config-dev
                  key: MYSQL_HOST
            - name: MYSQL_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config-dev
                  key: MYSQL_NAME
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config-dev
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-dev
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-dev
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config-dev
                  key: MYSQL_ROOT_HOST
            ports:
            - containerPort: 9000