apiVersion: v1
kind: Service
metadata:
  name: sports-platform-file-server
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: NodePort
  selector:
    run: sports-platform-file-server