apiVersion: v1
kind: Service
metadata:
  name: sports-platform-file-server-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  clusterIP: 10.104.34.38
  selector:
    run: sports-platform-file-server-service