name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dev-sports-platform-file-server:latest

      - name: Deploy to ArgoCD
        run: |
          argocd app create sports-platform-file-server-dev \
            --repo https://github.com/biuea3866/sports-platform-file-server.git \
            --path . \
            --dest-server http://localhost:8080 \
            --src ref=dev \
            --sync-policy automated \
            --self-heal \
          
          argocd app sync sports-platform-file-server-dev
