name: Gradle Build & k8s Deploy

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: [ "dev" ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Grant execute permission for gradlew
          run: chmod +x ./gradlew

        - name: Build with Gradle
          uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
          with:
            arguments: bootJar

        - name: Build the Docker image
          run: docker build -t biuea/life-sports-authn-server:latest .

        - name: Login to Docker Hub
          uses: docker/login-action@v2.1.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Docker hub publish
          run: docker push biuea/sports-platform:latest